export enum ErrorCode {
  VALIDATION_FAILED =
    'VALIDATION_FAILED',

  RESOURCE_NOT_FOUND =
    'RESOURCE_NOT_FOUND',

  DUPLICATE_RESOURCE =
    'DUPLICATE_RESOURCE',

  DATABASE_ERROR =
    'DATABASE_ERROR',

  UNAUTHORIZED =
    'UNAUTHORIZED',

  FORBIDDEN =
    'FORBIDDEN',

  INSUFFICIENT_PERMISSIONS =
    'INSUFFICIENT_PERMISSIONS',

  SERVICE_UNAVAILABLE =
    'SERVICE_UNAVAILABLE',

  INTERNAL_SERVER_ERROR =
    'INTERNAL_SERVER_ERROR',
}